In [4]:
import pandas as pd
import numpy as np

In [5]:
 data = {
    "asset": ["AAPL", "MSFT", "BTC", "ETH"],
    "price": [210, 450, 62000, 3400],
    "asset_type": ["stock", "stock", "crypto", "crypto"]
}

In [8]:
df_assets  =  pd.DataFrame(data)

In [14]:
df_assets.head()

  asset  price asset_type
0  AAPL    210      stock
1  MSFT    450      stock
2   BTC  62000     crypto
3   ETH   3400     crypto

In [15]:
df_assets.shape

(4, 3)

In [16]:
df_assets.columns

Index(['asset', 'price', 'asset_type'], dtype='object')

In [17]:
df_assets.dtypes

asset         object
price          int64
asset_type    object
dtype: object

In [19]:
data2 = [
    ["rent", 1600],
    ["food", 800],
    ["transport", 150],
    ["gym", 120]
]

In [23]:
df_expenses = pd.DataFrame(data2,columns=["category", "amount"])

In [24]:
df_expenses

    category  amount
0       rent    1600
1       food     800
2  transport     150
3        gym     120

In [26]:
df_expenses.columns

Index(['category', 'amount'], dtype='object')

In [30]:
income = 4000
df_expenses["share_of_income"] = df_expenses["amount"] / income * 100

In [31]:
df_expenses

    category  amount  share_of_income
0       rent    1600            40.00
1       food     800            20.00
2  transport     150             3.75
3        gym     120             3.00